fix

diff --git a/.github/workflows/clamav.yml b/.github/workflows/clamav.yml
--- a/.github/workflows/clamav.yml
+++ b/.github/workflows/clamav.yml
@@ -48,44 +48,44 @@ jobs:
         with:
           context: .
           platforms: linux/amd64
-          push: true
+          load: true
           tags: ${{ steps.docker_meta_img.outputs.tags }}
           labels: ${{ steps.docker_meta_img.outputs.labels }}
           build-args: |
             KEYCLOAK_VARIANT=${{ matrix.variant }}
 
-      # - name: Export Docker image as tar
-      #   run: |
-      #     docker save ghcr.io/${{ steps.lower-repo.outputs.repository }} -o image.tar
-      #     mkdir -p ${{ github.workspace }}/clamavscan
-      #     mv image.tar ${{ github.workspace }}/clamavscan/image.tar
+      - name: Export Docker image as tar
+        run: |
+          docker save ghcr.io/${{ steps.lower-repo.outputs.repository }} -o image.tar
+          mkdir -p ${{ github.workspace }}/clamavscan
+          mv image.tar ${{ github.workspace }}/clamavscan/image.tar
 
-      # - name: Run ClamAV scan
-      #   run: |
-      #     docker run --rm -v ${{ github.workspace }}/clamavscan:/scan clamav/clamav:latest clamscan /scan/image.tar > ${{ github.workspace }}/clamav-results-${{ matrix.variant }}.txt
+      - name: Run ClamAV scan
+        run: |
+          docker run --rm -v ${{ github.workspace }}/clamavscan:/scan clamav/clamav:latest clamscan /scan/image.tar > ${{ github.workspace }}/clamav-results-${{ matrix.variant }}.txt
 
-      # - name: Upload ClamAV scan results
-      #   if: ${{ always() }}
-      #   uses: actions/upload-artifact@v4
-      #   with:
-      #     name: clamav-results-${{ matrix.variant }}
-      #     path: clamav-results-${{ matrix.variant }}.txt
+      - name: Upload ClamAV scan results
+        if: ${{ always() }}
+        uses: actions/upload-artifact@v4
+        with:
+          name: clamav-results-${{ matrix.variant }}
+          path: clamav-results-${{ matrix.variant }}.txt
 
-      # - name: Check ClamAV scan result
-      #   run: |
-      #     if grep -q "/scan/image.tar: OK" ${{ github.workspace }}/clamav-results-${{ matrix.variant }}.txt; then
-      #       echo "No malware found for variant ${{ matrix.variant }}."
-      #     else
-      #       echo "::warning::Malware detected or scan failed for variant ${{ matrix.variant }}!"
-      #       cat ${{ github.workspace }}/clamav-results-${{ matrix.variant }}.txt
-      #       # exit 1
-      #     fi
+      - name: Check ClamAV scan result
+        run: |
+          if grep -q "/scan/image.tar: OK" ${{ github.workspace }}/clamav-results-${{ matrix.variant }}.txt; then
+            echo "No malware found for variant ${{ matrix.variant }}."
+          else
+            echo "::warning::Malware detected or scan failed for variant ${{ matrix.variant }}!"
+            cat ${{ github.workspace }}/clamav-results-${{ matrix.variant }}.txt
+            # exit 1
+          fi
           
-      # # - name: Push all scanned image tags to ghcr.io
-      # #   run: |
-      # #     echo "${{ steps.docker_meta_img.outputs.tags }}" | while read TAG; do
-      # #       docker push "$TAG"
-      # #     done
+      - name: Push all scanned image tags to ghcr.io
+        run: |
+          echo "${{ steps.docker_meta_img.outputs.tags }}" | while read TAG; do
+            docker push "$TAG"
+          done
 
       # - name: Build and push image to ghcr
       #   id: docker_push
