disable clamav

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -94,43 +94,43 @@ jobs:
           docker rm temp_scan_container
           rm -rf ${{ github.workspace }}/clamavscan/container_fs.tar
 
-      - name: Create ClamAV Socket dir
-        run: |
-          docker volume create sockets
+      # - name: Create ClamAV Socket dir
+      #   run: |
+      #     docker volume create sockets
 
-      - name: create logfile
-        run: |
-          touch ${{ github.workspace }}/clamav-results-${{ matrix.variant }}.txt
-          chmod ugo+rw ${{ github.workspace }}/clamav-results-${{ matrix.variant }}.txt
+      # - name: create logfile
+      #   run: |
+      #     touch ${{ github.workspace }}/clamav-results-${{ matrix.variant }}.txt
+      #     chmod ugo+rw ${{ github.workspace }}/clamav-results-${{ matrix.variant }}.txt
 
-      - name: Run ClamAV Update
-        run: |
-          docker run --rm -v ${{ github.workspace }}/clamavscan:/scan clamav/clamav:latest freshclam --datadir=/scan
+      # - name: Run ClamAV Update
+      #   run: |
+      #     docker run --rm -v ${{ github.workspace }}/clamavscan:/scan clamav/clamav:latest freshclam --datadir=/scan
 
-      - name: Run ClamAV start Deamon
-        run: |
-          docker run  --rm -v ${{ github.workspace }}/clamavscan:/scan -v sockets:/tmp clamav/clamav:latest &
+      # - name: Run ClamAV start Deamon
+      #   run: |
+      #     docker run  --rm -v ${{ github.workspace }}/clamavscan:/scan -v sockets:/tmp clamav/clamav:latest &
 
-      - name: Run ClamAV SCAN
-        run: |
-          docker run --rm -v ${{ github.workspace }}:/workdir -v ${{ github.workspace }}/clamavscan:/scan -v sockets:/tmp clamav/clamav:latest clamdscan /scan/container_fs -m -w --fdpass -l /workdir/clamav-results-${{ matrix.variant }}.txt -v --stdout
+      # - name: Run ClamAV SCAN
+      #   run: |
+      #     docker run --rm -v ${{ github.workspace }}:/workdir -v ${{ github.workspace }}/clamavscan:/scan -v sockets:/tmp clamav/clamav:latest clamdscan /scan/container_fs -m -w --fdpass -l /workdir/clamav-results-${{ matrix.variant }}.txt -v --stdout
 
-      - name: Upload ClamAV scan results
-        if: ${{ always() }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: clamav-results-${{ matrix.variant }}
-          path: clamav-results-${{ matrix.variant }}.txt
+      # - name: Upload ClamAV scan results
+      #   if: ${{ always() }}
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: clamav-results-${{ matrix.variant }}
+      #     path: clamav-results-${{ matrix.variant }}.txt
 
-      - name: Check ClamAV scan result
-        run: |
-          if grep -q "Infected files: 0" ${{ github.workspace }}/clamav-results-${{ matrix.variant }}.txt; then
-            echo "No malware found for variant ${{ matrix.variant }}."
-          else
-            echo "::warning::Malware detected or scan failed for variant ${{ matrix.variant }}!"
-            cat ${{ github.workspace }}/clamav-results-${{ matrix.variant }}.txt
-            exit 1
-          fi
+      # - name: Check ClamAV scan result
+      #   run: |
+      #     if grep -q "Infected files: 0" ${{ github.workspace }}/clamav-results-${{ matrix.variant }}.txt; then
+      #       echo "No malware found for variant ${{ matrix.variant }}."
+      #     else
+      #       echo "::warning::Malware detected or scan failed for variant ${{ matrix.variant }}!"
+      #       cat ${{ github.workspace }}/clamav-results-${{ matrix.variant }}.txt
+      #       exit 1
+      #     fi
 
       - name: Push scanned image to ghcr.io, if it passed
 
